/*
 * Name: QuizResults
 * Date: 10-06-2015 (DD-MM-YYYY)
 * Version: v1
 * Author: Sean van Wyk
 * Description: Program to display quiz results
 */
package edu.hdsb.gwss.sevw.ics3u.PerformanceTask;

import javax.swing.JLabel;

/**
 *
 * @author Sean
 */
public class QuizResultsSean extends javax.swing.JFrame {

    /**
     * Creates new form QuizResults
     */
    public QuizResultsSean(int score) {
        
        initComponents();
        labelNumerator.setText("" + score);
        if (score < 10) {
            labelPercentValue.setText("" + score + "0");
        } else {
            labelPercentValue.setText("10");
        }
        switch (score) {
            case 0:
                break;
            case 1:
                labelMessage.setText("Seriously! apply yourself.");
                break;
            case 2:
                labelMessage.setText("Apply for a job at McDonalds at IFailedComputerScience.ca.");
                break;
            case 3:
                labelMessage.setText("How many students does it take to complete a quiz. 3 apparently");
                break;
            case 4:
                labelMessage.setText("Almost to nearly kind of acceptable, Try harder");
                break;
            case 5:
                labelMessage.setText("Just made it, Lucky Bastard.");
                break;
            case 6:
                labelMessage.setText("I don't anything interesting to say this mark is nothing special");
                break;
            case 7:
                labelMessage.setText("You are 100% average");
                break;
            case 8:
                labelMessage.setText("You are 60% average.");
                break;
            case 9:
                labelMessage.setText("Well done, you got 9 multiple choice questions rigth, yay.");
                break;
            case 10:
                labelMessage.setText("ShowOff!");
                break;
        }
    }
    
    private QuizResultsSean() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelResults = new javax.swing.JLabel();
        javax.swing.JLabel labelScoreHeader = new javax.swing.JLabel();
        labelNumerator = new javax.swing.JLabel();
        labelOutOf = new javax.swing.JLabel();
        labelDenom = new javax.swing.JLabel();
        labelMarks = new javax.swing.JLabel();
        labelMessage = new javax.swing.JLabel();
        labelPercentageTitle = new javax.swing.JLabel();
        labelPercentValue = new javax.swing.JLabel();
        labelPercentSign = new javax.swing.JLabel();
        labelEndMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelResults.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        labelResults.setText("Results Page");

        labelScoreHeader.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelScoreHeader.setText("Final Score");

        labelNumerator.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelNumerator.setText("0");

        labelOutOf.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelOutOf.setText(" out of a possible");

        labelDenom.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelDenom.setText("10");
        labelDenom.setToolTipText("");

        labelMarks.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelMarks.setText("marks.");

        labelMessage.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelMessage.setText("If this is the mark you recieve this file must be broken");

        labelPercentageTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelPercentageTitle.setText("Percentage");

        labelPercentValue.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelPercentValue.setText("00");

        labelPercentSign.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelPercentSign.setText("%");

        labelEndMessage.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelEndMessage.setText("Thank you for testing enjoy the cake, it is not a lie, I promise.[o]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(labelResults, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMessage)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPercentageTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelPercentValue))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelScoreHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNumerator)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelOutOf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDenom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelMarks))
                                    .addComponent(labelPercentSign)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelEndMessage)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelResults, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScoreHeader)
                    .addComponent(labelNumerator)
                    .addComponent(labelOutOf)
                    .addComponent(labelDenom)
                    .addComponent(labelMarks))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPercentageTitle)
                    .addComponent(labelPercentValue)
                    .addComponent(labelPercentSign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMessage)
                .addGap(18, 18, 18)
                .addComponent(labelEndMessage)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizResultsSean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizResultsSean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizResultsSean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizResultsSean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizResultsSean(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDenom;
    private javax.swing.JLabel labelEndMessage;
    private javax.swing.JLabel labelMarks;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelNumerator;
    private javax.swing.JLabel labelOutOf;
    private javax.swing.JLabel labelPercentSign;
    private javax.swing.JLabel labelPercentValue;
    private javax.swing.JLabel labelPercentageTitle;
    private javax.swing.JLabel labelResults;
    // End of variables declaration//GEN-END:variables
}
