/*
 * Name: SchoolXMLGUI
 * Date: 22-05-2015 (DD-MM-YYYY)
 * Version: v1
 * Author: Sean van Wyk
 * Description: Program to write data in a XML Format
 import nu.xom.Serializer;

 */
package edu.hdsb.gwss.sevw.ics3u.U7;

import edu.hdsb.gwss.sevw.ics3u.Libraries.ArrayTools;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import nu.xom.Builder;

import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author Sean
 */
public class friendsReader extends javax.swing.JFrame {

    /**
     * Creates new form SchoolXMLGUI
     */
    public friendsReader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        header = new javax.swing.JLabel();
        importButon = new javax.swing.JButton();
        friendsList = new javax.swing.JComboBox();
        nameHeader = new javax.swing.JLabel();
        addressHeader = new javax.swing.JLabel();
        phoneHeader = new javax.swing.JLabel();
        emailHeader = new javax.swing.JLabel();
        namePrint = new javax.swing.JLabel();
        addressPrint = new javax.swing.JLabel();
        phonePrint = new javax.swing.JLabel();
        emailPrint = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Friend Database");

        importButon.setText("Import");
        importButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButonActionPerformed(evt);
            }
        });

        friendsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsListActionPerformed(evt);
            }
        });

        nameHeader.setText("Name:");

        addressHeader.setText("Address:");

        phoneHeader.setText("Phone:");

        emailHeader.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(importButon))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameHeader)
                            .addComponent(friendsList, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressHeader)
                            .addComponent(phoneHeader)
                            .addComponent(emailHeader)
                            .addComponent(namePrint)
                            .addComponent(phonePrint)
                            .addComponent(emailPrint)
                            .addComponent(addressPrint))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(friendsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameHeader)
                .addGap(7, 7, 7)
                .addComponent(namePrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressPrint)
                .addGap(11, 11, 11)
                .addComponent(phoneHeader)
                .addGap(13, 13, 13)
                .addComponent(phonePrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    File file = new File("friends.xml");
    Builder builder = new Builder();
    String[] list;
    Document doc;
    Element friends;
    Elements friend;
    private void importButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButonActionPerformed
        try {
            doc = builder.build(file);
        } catch (Exception e) {
            System.out.println(e);
        }
        friends = doc.getRootElement();
        friend = friends.getChildElements();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        list = new String[friend.size()];
        for (int i = 0; friend.size() > i; i++) {
            model.addElement(friend.get(i).getFirstChildElement("name").getValue());
            list[i]=friend.get(i).getFirstChildElement("name").getValue();

        }
        friendsList.setModel(model);
        namePrint.setText(friend.get(0).getFirstChildElement("name").getValue());
        addressPrint.setText(friend.get(0).getFirstChildElement("address").getValue());
        phonePrint.setText(friend.get(0).getFirstChildElement("phone").getValue());
        emailPrint.setText(friend.get(0).getFirstChildElement("email").getValue());

    }//GEN-LAST:event_importButonActionPerformed

    private void friendsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsListActionPerformed
        JComboBox friendList = (JComboBox) evt.getSource();
        String friendName = (String) friendList.getSelectedItem();
        int index=0;
        
        for (int i = 0; index == 0 && i < list.length; i++) {
            if (list[i].equals(friendName)) {
                index= i;
            }
        }

        namePrint.setText(friend.get(index).getFirstChildElement("name").getValue());
        addressPrint.setText(friend.get(index).getFirstChildElement("address").getValue());
        phonePrint.setText(friend.get(index).getFirstChildElement("phone").getValue());
        emailPrint.setText(friend.get(index).getFirstChildElement("email").getValue());

    }//GEN-LAST:event_friendsListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolXMLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolXMLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolXMLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolXMLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new friendsReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressHeader;
    private javax.swing.JLabel addressPrint;
    private javax.swing.JLabel emailHeader;
    private javax.swing.JLabel emailPrint;
    private javax.swing.JComboBox friendsList;
    private javax.swing.JLabel header;
    private javax.swing.JButton importButon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nameHeader;
    private javax.swing.JLabel namePrint;
    private javax.swing.JLabel phoneHeader;
    private javax.swing.JLabel phonePrint;
    // End of variables declaration//GEN-END:variables
}
